services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=secretpassword
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secretpassword
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
